DataBase = {

"SliderImages":"https://scontent.fixc7-1.fna.fbcdn.net/v/t39.30808-6/275300624_1178988679312314_2530405338295637793_n.jpg?stp=dst-jpg_s720x720&_nc_cat=108&ccb=1-5&_nc_sid=8bfeb9&_nc_ohc=8A8UMQ_TdqEAX-EWVup&_nc_ht=scontent.fixc7-1.fna&oh=00_AT-jbig7cSG3T5J36JDpx-nJkVtVUP-kKJHx4yXGnJIJig&oe=622B824A",
"News":"Admission is open "

}

Teachers = (
['1', 'Mrs. Vinodita Sankhyan', 'Principal', 'M.A.,B.Ed., UGC (NET)'],
['2', 'Ms.Alka', 'Teacher', 'M.A,B.Ed.'],
['3', 'Ms.Alka Rani', 'Teacher', 'M.A.,B.Ed.'],
['4', 'Ms.Alpana Kohli', 'Teacher', 'M.A.B.Ed,Cert.(French)'],
['5', 'Ms. Anu Khanna', 'Teacher', 'M.A.,B.Ed.'],
['6', 'Ms.Amardeep Kaur', 'Teacher', 'M.A,B,Ed.,PGDCA'],
['7', 'Ms.Amarjit Kaur', 'Teacher', 'M.A.,B.Ed.'],
['8', 'Ms.Amarjit Kaur', 'Teacher', 'M.A, B.Ed'],
['9', 'Ms.Anjali Sandal', 'Teacher', 'M.Com,B.Ed.'],
['10', 'Ms.Anju Chaudhary', 'Teacher', 'M.A., B.Ed.'],
['11', 'Ms.Anuradha', 'Teacher', 'Msc(Maths)'],
['12', 'Ms.Anureet', 'Teacher', 'M.A.(Eco)N.T.T. ,B.Ed'],
['13', 'Ms.Aparna Sharma', 'Teacher', 'M.A,B.Ed.'],
['14', 'Ms.Asha Rani', 'Teacher', 'M.A.M.Ed'],
['15', ' Ms.Atika', 'Teacher', 'M.Phil'],
['16', ' Ms.Atul Sharma', 'Teacher', 'M.Sc.,B.Ed.'],
['17', 'Ms.Bhawna Sharma', 'Teacher', 'Msc., B.Ed'],
['18', 'Ms.Bhupinder Kaur', 'Teacher', 'M.A. B.Ed.'],
['19', 'Ms.Chanda Bahl', 'Teacher', 'M.A.,B.Ed.'],
['20', 'Ms.Davinder Singh', 'Teacher', 'Dip. In C.P.Ed.'],
['21', 'Ms.Deepak', 'Teacher', 'M.A.,B.Ed.,PGDCA'],
['22', ' Ms.Deepika Monga', 'Teacher', 'M.Com,B.Ed.'],
['23', 'Ms.Devendra Singh', 'Teacher', 'B.Tech (IT), MSc. (Physics)'],
['24', 'Ms.Garima Sharma', 'Teacher', 'B.Sc., M.sc.(Comp.Sci) ,(B.Ed. Persuing)'],
['25', 'Ms.Garima Thakur', 'Teacher', 'M.A.(Phy.Edu.)'],
['26', 'Ms.Gitika Oberoi', 'Teacher', 'M.A. (Fine arts)'],
['27', 'Ms.Gulraj Bhagat', 'Teacher', 'M.Com(B.Ed.)'],
['28', 'Ms.Gauri Gupta', 'Teacher', 'M.A.,B.Ed.'],
['29', 'Ms.Harish Kurl', 'Teacher', 'M.Sc.(maths),B.Ed'],
['30', 'Ms.Harpreet Kaur', 'Teacher', 'M.Sc.,B.Ed.'],
['31', 'Ms.Harpreet Kaur -Pbi', 'Teacher', 'M.A,B.Ed'],
['32', 'Ms.Inderjeet', 'Teacher', '+2,Vishard(Apr-15)'],
['33', 'Ms.Inderpreet Kaur', 'Teacher', 'M.A,B.Ed.'],
['34', 'Ms.Isha Sharma', 'Teacher', 'M.A,B.Ed'],
['35', 'Ms.Jasleen Arora', 'Teacher', 'B.Com, B.Ed'],
['36', 'Ms.Jatinder Kaur', 'Teacher', 'B.P.Ed'],
['37', 'Ms.Jatinder Kaur(Gym. Coach)', 'Teacher', 'B.A., C.P.Ed.'],
['38', 'Ms.Jatinder Kaur(Hindi)', 'Teacher', 'M.A,B.Ed.'],
['39', 'Ms. Jyoti', 'Teacher', 'M.Lib,B.Ed., M.A.(Hist.)'],
['40', 'Ms.Jyoti Arora', 'Teacher', 'M.A,M.Phil,B.Ed.'],
['41', ' Ms.Jyoti Sharma', 'Teacher', 'M.A.,B,Ed'],
['42', ' Ms.Kavita Joshi', 'Teacher', 'M.Sc.,B.Ed.'],
['43', 'Ms.Kanu ', 'Teacher', 'M.Sc B.Ed'],
['44', 'Ms.Karan Diana Sandhu', 'Teacher', 'M.Com,B.Ed.'],
['45', ' Ms.Kiran Sharma', 'Teacher', 'M.A. B.Ed.,(M.A-punjabi persuing)'],
['46', 'Ms.Komal Sharma', 'Teacher', 'MCA'],
['47', 'Ms.Lovepreet Kaur', 'Teacher', 'M.Sc.,B.Ed.'],
['48', 'Ms.Madhu Manchanda', 'Teacher', 'M.A.,B.Ed.,M.A.(Pol.Sci. Persuing)'],
['49', 'Ms.Mamta Rampal', 'Teacher', 'B.C.A,MCA'],
['50', 'Ms.Mannu Mehra', 'Teacher', 'M.Sc.,B.Ed.'],
['51', 'Ms.Manpreet Kaur', 'Teacher', 'M.A. (Fine arts)'],
['52', 'Ms. Megha Khanna', 'Teacher', 'M.A.,B.Ed'],
['53', 'Ms.Mehak Khosla', 'Teacher', 'M.A, B.Ed'],
['54', 'Ms. Mohit Kumar', 'Teacher', 'Btech (ECE)'],
['55', ' Ms.Monika Sareen', 'Teacher', 'M.A, B.Ed'],
['56', 'Ms.Monika Khindri', 'Teacher', 'M.A, B.Ed'],
['57', 'Mr.Mukesh', 'Teacher', 'M.Com,C.A.-inter, UGC,B.Ed.'],
['58', 'Ms.Mukta Mahajan', 'Teacher', 'M.Com, MBA,B.Ed.'],
['59', 'Ms.Navneet Kaur', 'Teacher', 'M.A, B.Ed'],
['60', 'Ms.Neena Sharma', 'Teacher', 'B.A.,B.Ed.'],
['61', 'Ms.Neha Khanna', 'Teacher', 'B.A.B.Ed, (M.A.)'],
['62', 'Ms.Neha', 'Teacher', 'M.Sc.,B.Ed.'],
['63', 'Ms.Nidhi Duggal', 'Teacher', 'M.Com, B.Ed.'],
['64', 'Ms.Nidhi Ohri', 'Teacher', 'M.A.(Eng.),B.Ed.'],
['65', ' Ms.Nidhi Sharma', 'Teacher', 'B.A.,B.Ed,Visharad'],
['66', 'Ms.Nidhi Saggar', 'Teacher', 'BAMS'],
['67', 'Ms.Pallavi Verma', 'Teacher', 'M.C.A.'],
['68', 'Ms.Paramjit Mehendiratta', 'Teacher', 'B.A,B.Ed'],
['69', 'Ms.Parul', 'Teacher', 'M.A,M.Phil,B.Ed.'],
['70', 'Ms. Parveen Arora', 'Teacher', 'M.Sc.B.Ed.'],
['71', 'Ms.Payal Mahajan', 'Teacher', 'M.A.,B.Ed.'],
['72', 'Ms.Payal Kapoor', 'Teacher', 'M.A.,B.Ed, M.A. (Hist.)'],
['73', 'Ms.Pooja', 'Teacher', 'M.Com,B.Ed.'],
['74', 'Ms.Pooja Kapoor', 'Teacher', 'B.A Hons.'],
['75', ' Ms.Pooja Jaitly', 'Teacher', 'B.A. B.Ed.'],
['76', 'Ms.Poonam Bhalla', 'Teacher', 'M.A.,B.Ed.'],
['77', 'Ms. Poonam Verma', 'Teacher', 'M.A (Fine Arts)'],
['78', 'Ms.Pratibha Bareja', 'Teacher', 'M.A.,B.Ed.'],
['79', 'Ms.Rachna Mahajan', 'Teacher', 'B.A.,B.Ed., NTT'],
['80', 'Ms.Radhika Arora', 'Teacher', 'M.Com,M.Ed.UGC(NET)'],
['81', 'Ms.Radhika ', 'Teacher', 'B.A, MA'],
['82', 'Ms.Rajbir Kaur', 'Teacher', 'M.A.,B.Ed.'],
['83', 'Ms R.amanpreet Kaur', 'Teacher', 'M.Com,B.Ed.'],
['84', 'Ms.Ranjana Talwar', 'Teacher', 'M.A., B.Ed'],
['85', 'Mr.Ranjit Singh', 'Teacher', 'M.P.Ed.,M.Phill'],
['86', 'Ms.Reena Devi ', 'Teacher', 'MA, B.Ed'],
['87', 'Ms.Reena Kashyap', 'Teacher', 'M.Sc.,B.Ed.,PGDCA'],
['88', 'Ms.Rekha', 'Teacher', 'M.Com,B.Ed.'],
['89', 'Ms.Renu Batra', 'Teacher', 'B.Com,M.A, B.Ed.'],
['90', 'Ms.Richa Sharma', 'Teacher', 'B.Com, MBA,B.Ed.'],
['91', 'Ms.Ridhima Kapoor', 'Teacher', 'MBA'],
['92', 'Ms.Rita Singh', 'Teacher', 'B.A.Visharad, Bhaskar'],
['93', 'Ms.Rishbi Rawlley', 'Teacher', 'B.Com,B.Ed.'],
['94', 'Ms.Ritika Mahajan', 'Teacher', 'M.Com'],
['95', 'Ms.Ritu Sharma', 'Teacher', 'M.A.,B.Ed.'],
['96', 'Ms.Rupa Nagpal', 'Teacher', 'M.A., B.Ed.'],
['97', 'Ms.Sakshi Seth', 'Teacher', 'M.A,B.Ed.'],
['98', 'Ms.Saloni Razdan', 'Teacher', 'M.A. B.Ed,PGDCA'],
['99', 'Ms.Sandeep Kumar', 'Teacher', 'B.A, Visharad, Bhaskar'],
['100', 'Ms.Sangeeta Chopra', 'Teacher', 'B.A.'],
['101', 'Ms.Sania Mehta', 'Teacher', 'M.Lib.'],
['102', 'Ms.Sarita Sharma', 'Teacher', 'M.Sc.,B.Ed.,PGDCA'],
['103', ' Ms.Sarita', 'Teacher', 'M.A.,B.Ed.'],
['104', 'Ms. Shaina Sharma', 'Teacher', 'Bsc(eco), BE.d'],
['105', 'Ms.Shashi Kant Sharma', 'Teacher', 'LLM, B.Ed.'],
['106', 'Ms.Shaveta Khosla', 'Teacher', 'M.A, B.Ed'],
['107', 'Ms.Shifali Galhotra', 'Teacher', 'M.A. B.Ed.'],
['108', 'Ms.Shikha Mehra', 'Teacher', 'M.A.,B.Ed.'],
['109', 'Ms.Shivani Abrol', 'Teacher', 'B.Sc.,B.Ed..M.Sc.'],
['110', 'Ms.Shivani', 'Teacher', 'B.A.,B.Ed.,M.A.'],
['111', 'Ms.Shivani Sharma', 'Teacher', 'MA., B.Ed'],
['112', 'Ms.Shruti Sharma', 'Teacher', 'B.A , B.Ed'],
['113', 'Ms.Simmi Arora', 'Teacher', 'M.Sc.,B.Ed.'],
['114', 'Ms.Simmi Tandon', 'Teacher', 'B.A.,B.Ed.'],
['115', 'Ms.Sonia Sharma', 'Teacher', 'M.A,B.Ed.,PGDCA'],
['116', ' Ms.Sujata', 'Teacher', 'M.Sc,B.Ed.'],
['117', ' Ms.Sukhreet Kaur', 'Teacher', 'M.Sc.,M.Ed.'],
['118', 'Ms.Sukhjeet', 'Teacher', 'B.A.B.Ed.'],
['119', 'Ms.Sukhvinder', 'Teacher', 'M.A. , B.Ed.'],
['120', 'Ms.Sumiti Gupta', 'Teacher', 'M.Sc.,B.Ed.'],
['121', 'Ms.Sunita Sharma', 'Teacher', 'M.A,B.Ed, M.Phil,M.Ed.'],
['122', 'Ms.Teena Mahajan', 'Teacher', 'M.A.,B.Ed., PGDCA'],
['123', 'Ms.Tript Kaur', 'Teacher', 'B.Sc. B.Ed.'],
['124', 'Ms.Twinkle Kapoor', 'Teacher', 'B.A.,B.Ed'],
['125', 'Ms.Vandana Sharma', 'Teacher', 'B.Com,B.Ed.,PGDCA,(M.A. Persuing)'],
['126', 'Ms.Vandana Malhotra', 'Teacher', 'Dip. Fashion Designing, B.A.,B.Ed'],
['127', 'Ms.Varinder Kaur', 'Teacher', 'M.A,M.Ed.,UGC(NET)'],
['128', 'Ms.Veenu Sharma', 'Teacher', 'B.A.,B.Ed.'],
['129', 'Mr.Vishal Arora', 'Teacher', 'M.A.,Visharad'],
['130', ' Mr.Viney Chanana', 'Teacher', 'Btech(Ece), Msc(Physics)'],
['131', ' Mr.Uttam Dash', 'Teacher', 'Matric']
)
links = ["http://www.shriramashramps.org/assets/img/clogo/1.png",
"http://www.shriramashramps.org/assets/img/clogo/2.png",
"http://www.shriramashramps.org/assets/img/clogo/3.png",
"http://www.shriramashramps.org/assets/img/clogo/4.png",
"http://www.shriramashramps.org/assets/img/clogo/5.png",
"http://www.shriramashramps.org/assets/img/clogo/6.png",
"http://www.shriramashramps.org/assets/img/clogo/7.png",
"http://www.shriramashramps.org/assets/img/clogo/8.png",
"http://www.shriramashramps.org/assets/img/clogo/9.png",
"http://www.shriramashramps.org/assets/img/clogo/10.png",
"http://www.shriramashramps.org/assets/img/clogo/11.png",
"http://www.shriramashramps.org/assets/img/clogo/12.png"]
